version: '3'

services:
  frontend:
    container_name: smarthome-frontend
    image: smarthome-frontend
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - '80:3000'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      OPEN_WEATHER_MAP_API_KEY: ${OPEN_WEATHER_MAP_API_KEY}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
