version: '3'

services:
  frontend:
    container_name: smarthome-frontend
    image: smarthome-frontend
    build: ./client/.
    command: npm start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      WEATHER_API_KEY: 7469b1a4943c4641ae584401222504
      NEXT_PUBLIC_API_URL: http://localhost:3001/

  backend:
    container_name: smarthome-backend
    image: smarthome-backend
    build: ./server/.
    command: npm start
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      DB_CONNECTION_STRING: mongodb://database:27017/?retryWrites=true&w=majority
      DB_USER: root
      DB_PASS: root

  database:
    container_name: smarthome-database
    image: mongo:latest
    ports:
      - 27017:27017

  dashboard:
    image: adminer
    restart: always
    ports:
      - 8080:8080
