version: '3'

services:
  frontend:
    container_name: smarthome-frontend
    image: chris-smarthome
    build: .
    command: npm start
    restart: unless-stopped
    ports: 
      - "80:3000"
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      OPEN_WEATHER_MAP_API_KEY: 4e973c29bc94ec6890e51f6c37f8eab5
      NEXT_PUBLIC_API_URL: http://chris-raspberrypi
