version: '3'

services:
  frontend:
    container_name: smarthome-frontend
    image: smarthome-frontend
    build: ./client/.
    command: npm start
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      WEATHER_API_KEY: WEATHER_API_KEY
      NEXT_PUBLIC_API_URL: NEXT_PUBLIC_API_URL
      JWT_SECRET: JWT_SECRET

  backend:
    container_name: smarthome-backend
    image: smarthome-backend
    build: ./server/.
    command: npm start
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
      DB_CONNECTION_STRING: DB_CONNECTION_STRING
      DB_USER: DB_USER
      DB_PASS: DB_PASS
      JWT_SECRET: JWT_SECRET
  database:
    container_name: smarthome-database
    image: mongo:latest
    environment:
      TZ: Europe/Berlin
      MONGO_INITDB_ROOT_USERNAME: MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: MONGO_INITDB_ROOT_PASSWORD
    ports:
      - '27017:27017'
