version: '3'

services:
  frontend:
    container_name: smarthome-backend
    image: smarthome-backend
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      TZ: Europe/Berlin
      NODE-ENV: production
